spring.application.name=backend
server.servlet.session.cookie.same-site=strict

spring.datasource.url=jdbc:postgresql://localhost:5432/Coinlytics
spring.datasource.username=postgres
spring.datasource.password=Santanu@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
server.port=5000
spring.jpa.hibernate.ddl-auto=update